### ISSUE TITLE
Player can get stuck in geometry/holes

### ISSUE THREAD

**Issue by jandd661** [UnityTechnologies/open-project-1#228]
If there is a "hole" or uneven surface, the player can get stuck. This is because the state machine enters a Sliding state and that state does not have a transition to JumpAscending.

**Expected behaviour**
The player should be able to jump while sliding.

**To Reproduce**
1. Find a hole and get in it. See picture.

![Unity_HEC6yC7Of6](https://user-images.githubusercontent.com/74697341/100497140-a3147300-3116-11eb-9a93-d6996b4bd560.png)

**Comment by jandd661** [comment]
PR for fix: #227

**Comment by ciro-unity** [comment]
I am aware of that spot in the map which makes the player stuck, and yes, this technically fixes it.
But it also kind of defeats the purpose of sliding? In the beginning of the project we created the sliding state as a way to prevent the player from walking up very steep geometry, but if they can jump while sliding now they can jump upstream (like a salmon :D).

So I'm reluctant to "fix" this. Maybe one way to fix it is to validate that, even if sliding, the player is not moving. Then you could allow a jump (or just put it in the Idle state). But then you would have to patch the Idle state to make sure it doesn't start sliding again in the following frame 🤔 
I think it's a bit of a rabbit hole.

Can't we just think geometry so that we avoid these edge cases, like the one which is in that scene now? We just need to make sure we don't have steep pits like that.

Thoughts?

**Comment by jandd661** [comment]
@ciro-unity I agree. This "fix" does not prevent the player from jumping up steep slopes (salmoning :D). Which currently allowed anyways. As that seems to be an unwanted behaviour than this fix is probably not ideal then. 

Currently, _"IsSliding"_ is based only on the Angle of the normal underneath the player which would infer that the character controller is "sliding" the character (and it is) but, in the case of our hole, the character never stops sliding even though there is no movement. It seems to me that; to be "sliding" you need to be moving as well as on a steep slope like you pointed out.

The _"IsMoving"_ is based on the player input and not if the character is actually moving (as far as I can tell).

**Options:**

1. Add a _"IsActuallyMoving"_ (or something) condition, that is based on the controller's `velocity.sqrMagnitude` that could be added to the _"Sliding"_ state. **Or...**

2. Add the `velocity.sqrMagnitude` check to the _"IsSliding"_ condition. **Or...**

3. Tell the level designers not to make holes/traps and we all go on with our day :D lol.

I'm currently expweimenting with option 1.

**Comment by jandd661** [comment]
OK, so I updated the PR #227 with a proposed fix for this _"issue."_ It adds IsActuallyMovingSO and an updated PigChef Transition Table. My testing has been very successful. I must say I really like this State Machine.

**IsActuallyMovingSO** evaluates character movement by the character `controller's velosity.sqrMagnitude`. Returns true if the character controller is moving beyond the threshold. Characters can no longer jump while sliding but can jump if they get stuck.
