### ISSUE TITLE
Mouse pointer erratic behaviour

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#245]
**Short description**
Sometimes, the camera spins very fast when using the mouse to control the camera, even if the mouse is moved by a tiny fraction.

**Expected behaviour**
The camera should follow the speed of movement of the mouse.

**To Reproduce**
1. Open the scene "TestingGround"
2. Press Play
3. Once the game is in Play Mode, hold down the RMB and move the mouse left or right by a very tiny amount.
4. Notice the camera spins around a full circle, before resuming at the right speed.

**Notes**
- [See this video for an example of the issue occurring](https://youtu.be/fGTnzSzSmrI)

**Comment by kgc00** [comment]
hi @ciro-unity , i just saw this- we could just have mouse movement without RMB to sidestep this.  sound good?  I'm also down to debug if you'd like.

**Comment by adoart** [comment]
It looks like it depends where the click starts, the further from the center bigger the rotation, @ciro-unity clicked once close to the center and rotation was little. That's what I got from the video...

**Comment by khush2o2o** [comment]
I known this bus to how to solve...

**Comment by drbier1729** [comment]
Just tried to check this out but I'm unable to replicate the issue. 

I'm guessing that maybe the InputReader or InputSystem isn't updating the cursor's position when it jumps to the center when the cursor is locked (in CameraManager.cs). This causes the mouse delta on the first frame when the mouse is moved after enabling camera controls to be crazy high since it is calculating the difference between the position where the RMB was clicked and the center of the frame.

I'm pretty new to Unity so this might be incorrect, but hopefully this noticing is helpful! I'll keep working on it but without being able to recreate it, I'm not optimistic about producing a fix.

**Comment by ErikBehar** [comment]
> I have an idea to slove this bug...

Please provide the idea in writing or a link to the PR, stating that you know how to solve a bug with no further info is not useful to anybody.

**Comment by ErikBehar** [comment]
ok so I think @drbier1729 has it correct ... you can more easily replicate the issue, by popping out the game window, then click outside so the window looses focus and then click back into the window to get focus, then rm on the edge of the window. You will get the crazy spin and yeah I think its due to the initial difference. 

with the above steps you can replicate the issue many times within 1 play session.

**Comment by davejrodriguez** [comment]
Could someone who was able to reproduce the bug test #249?

**Comment by drbier1729** [comment]
@ErikBehar Cool! Thanks for finding a better way to replicate it. And I was thinking the same thing for a potential workaround, but there was no way for me to test it earlier today haha.

@davejrodriguez I'll check out your work tomorrow morning if I can recreate the bug using the steps ErikBehar suggested.

**Comment by ErikBehar** [comment]
I think some of what @davejrodriguez  did is probably good, but needs a bit more work ... I've added the simple fix mentioned above meanwhile.
