### ISSUE TITLE
Total Progress in LocationLoader.TrackLoadingProgress is assigned wrong value

### ISSUE THREAD

**Issue by Bvanderwolf** [UnityTechnologies/open-project-1#288]
**Short description**
Total progress isn't assigned the value of it being divided by load operations.Length. Now it will exit the while loop to early with multiple loading operations because the progress of each operation is added but total progress is never divided by load operations.length.

**Notes**
https://github.com/UnityTechnologies/open-project-1/blob/72e45ba5b0c0425c8ffdef24f85b6257459425d2/UOP1_Project/Assets/Scripts/SceneManagement/LocationLoader.cs#L174

Adding the assignment operator should fix this problem:
_loadingProgressBar.fillAmount = totalProgress /= _scenesToLoadAsyncOperations.Count;

or:

 totalProgress = Mathf.Clamp01(totalProgress / _scenesToLoadAsyncOperations.Count);

**Comment by amel-unity** [comment]
Hi @Bvanderwolf , thanks a lot for testing. We did some major changes on the loading system in the game, currently we don't track the total progress of the scenes to load anymore. Instead, we just check if the loading of all the scenes is done. Since the scenes in our game will not be huge, we don't expect that the loading screen will be shown for so long. We will just show a spinning logo without necessary showing how long we will wait for the scenes to load. 
Again thanks a lot for mentioning the issue and proposing a potential solution but I will have to close it.
