### ISSUE TITLE
Picking Up items sometimes throws `NullReferenceException`

### ISSUE THREAD

**Issue by Treslina** [UnityTechnologies/open-project-1#322]
**Short description**
Picking up an item after `Attack` animation playing is causing `NullReferenceException` and prevent picking up the item. Also while picking up animation is playing, pressing the `E` button again throws a `NullReferenceException`.

**Expected behaviour**
Don't throw an exception and pick up the item.

**To Reproduce**
1. Walk into a `CollectibleItem` and see the interaction UI which tells you to pick up the item by pressing the `E` button.
2. Press the attack button.
3. While animation is playing and your crane is in front of you press the `E` button.
4. Game throws an exception and can't pick up the item.

Steps to reproduce the another behavior:
1. Walk into a `CollectibleItem` and see the interaction UI which tells you to pick up the item by pressing the `E` button.
2. Press the `E` button.
3. While pick up animation is playing press the `E` button.
4. Game throws an exception.

<img width="675" alt="Screen Shot 2021-01-25 at 00 55 14" src="https://user-images.githubusercontent.com/7457284/105644713-1254dc00-5ea8-11eb-83b8-fabe00db8c6b.png">

<img width="676" alt="Screen Shot 2021-01-25 at 00 59 43" src="https://user-images.githubusercontent.com/7457284/105644805-9eff9a00-5ea8-11eb-8bac-b3cec71cca59.png">

**Notes**
I thought some solutions to that and I'd like to discuss them and contribute to the project 😊

**Comment by treivize** [comment]
Hi @Treslina,

Thanks to raise this issue, you have found it too! Indeed there is an issue with the current interaction manager. I guess, you have found the root cause of this issue looking at your scenario. Actually I have already opened a PR to propose a fix to this issue in addition to the capability to pickup multiple objects without having to move the character to force a new collider entry with interaction manager: [PR](https://github.com/UnityTechnologies/open-project-1/pull/301)

Do not hesitate to propose your own implementation or some comments to mine! :)

**Comment by Treslina** [comment]
Hello @treivize! 😊 

I didn't see the PR, I just looked at the issues sorry about that 🤦  I looked at your code and it looks great! I thought more basic fixes like, setting `_currentInteractableObject` only on `if-else` statements in `OnTriggerEnter` or  making `Interaction` collider to trigger only `Interactable` objects using layers etc. ✋

**Comment by amel-unity** [comment]
Hi @Treslina ! Thanks a lot for testing. I also noticed the issue and thought about using layers too. @treivize solutions works so I will merge it, thanks for proposing the PR :)
