### ISSUE TITLE
Current scene/quest/attack workflow will not work with the Bundles - game is not scalable

### ISSUE THREAD

**Issue by studentutu** [UnityTechnologies/open-project-1#331]
The issue with asset bundles and build in asset bundle pipeline is as follows :
1) All assets that are on the scene and or referenced by the scene (prefabs from resources/scriptable object from the project itself, textures, sound clips etc.) are copied into a bundle.  
There are no original references inside the bundle itself to the assets that you are seeing inside the  Editor /Editor Playmode.

That means - with the current workflow, there will be another scriptable object for each scriptable object reference in the scene in the memory so the player will never get the notification from bundles scene (scriptable object inside the bundle scene has no reference to the application scriptable object that is created at runtime).

To mitigate this issue - you need to create a persistent serialized value - sort of like GUID based reference https://github.com/Unity-Technologies/guid-based-reference

As a result - you will actually be better without the hard referencing of the scriptable objects itself, instead, the GUID based workflow will take care of finding the right asset for you.

**Comment by ciro-unity** [comment]
Hey @studentutu, thanks for bringing this up. We actually already discussed it in the forums. User peter77 brought it up.
I double checked with an expert in Addressables, so I'll reply here and there with the same message:

The Addressables system tracks dependencies of objects. If you reference a ScriptableObject from a GameObject in a scene, and you  reference the same SO from another GO in another Scene, the system knows it the same SO.

When we pack Scenes into Bundles, it's important to mark the SOs as Addressables.
- If they are, then the system will recognise the dependency and make it so that (for instance) SceneA, contained maybe in Level1Bundle, correctly references SO1 in a certain AssetBundle we'll call SOBundle. SceneB (contained in Level2Bundle) also references SO1 in SOBundle. When requesting the load of either scene, SOBundle will be loaded too.
- If the SOs are not explicitly marked as Addressables, they will be still pulled in these bundles because they are still a dependency. But this time they will be duplicated, giving the issue that you are describing.

So, we just need to mark things as Addressables correctly. Makes sense?

(I'll close the issue soon)

**Comment by studentutu** [comment]
@ciro-unity yep, thank you! Could you make a list of the issues that were inside the forum that were critical and what was a  solution? Something like a github ticket with a list of issues the project encountered along the way?

**Comment by ciro-unity** [comment]
Sorry, I thought it was quick to find. Here's a link to the discussion: https://forum.unity.com/threads/event-system-and-addressables.1028671/
It's the same concern you brought up, and the solution is the one described above.

What do you mean by "list of issues"? If you mean issues in general, they are browsable here (https://github.com/UnityTechnologies/open-project-1/issues) and filtering by closed.

**Comment by studentutu** [comment]
@ciro-unity how about the issue with all of the major systems in place, something like a retrospective issue? 
This will help visualize which problems were tackled first and which raised another set of issues and so on. 
Something like a retrospective of the project in general. 
Which rules/standards were introduced and what was the purpose of it. 
Very powerful and it will help tremendously for the upcoming projects.

**Comment by ciro-unity** [comment]
Forgot to close this one. It's a non-issue now thanks to how we organised the Addressable Groups.

We actually mentioned situations like this in our recently published Devlog:
https://www.youtube.com/watch?v=XIHINtB2e1U

Thanks, closing!
