### ISSUE TITLE
SpawnSystem no longer works as the default spawn location

### ISSUE THREAD

**Issue by rcarag** [UnityTechnologies/open-project-1#333]
The recent modifications in SpawnSystem to allow multiple entry/exit points seems to have broken the ability to use SpawnSystem on its own as a default spawn location.

The problem happens because the SpawnSystem's transform is not included in the results of `GameObject.FindGameObjectsWithTag("SpawnLocation")` in the `SpawnPlayer()` method. As a result, when a scene without other spawn locations is played directly in the editor (ex. TestingGround_Small), the SpawnSystem will fail to find a spawn location, and the player will not be spawned.

I'm creating a PR to workaround this issue.

**Comment by AlexandreGheraibia** [comment]
Hi, 
I looked in the spawnSystem file and saw this call :
FindSpawnIndex (_pathTaken? .Path ?? null) why not just put FindSpawnIndex (_pathTaken? .Path)
According to stackoverflow, pathTaken? .Path means that if PathTaken == null then return null else return pathTaken.Path. 
 and A ?? B means if A! = null then A otherwise B.

**Comment by ciro-unity** [comment]
Is this even still broken? I am playing the build from `main`, and I can spawn fine in any scene, including "Empty_Location" (which is like the simplest playable scene we have).

**Comment by ciro-unity** [comment]
I think we decided that this issue is no longer valid. Closing!
