### ISSUE TITLE
I think I have been hacked is there anyway you can get rid off the hack?🙏

### ISSUE THREAD

**Issue by 0479010347** [UnityTechnologies/open-project-1#93]
I think I have been hacked is there anyway you can get rid off the hack?🙏

- __Originally posted by @0479010347 in https://github.com/bit defender/bddisasm/issues/8#issuecomment-710008694__

**Comment by 0479010347** [comment]
[helpmeplease](****)

**Comment by mccorkle** [comment]
This is the wrong forum to be asking for help if your computer has been compromised by hackers.  

If you are confused about why you are receiving these notifications, it is because you are "watching" the github repo for the Unity Open-Project-1.  If you would like to no longer get them, just un-watch this repo.
